# Get-ChildItem -Recurse -Depth 2 -File | Select-Object FullName
# mkdocs gh-deploy
# mkdocs serve | build

site_name: Java | micro services | Spring Boot
site_url: https://lekhrajdinkar.github.io/microservices-java
site_author: Lekhraj Dinkar
site_author_url: https://www.linkedin.com/in/lekhraj-dinkar-25872140/
site_logo: images/logo.png
site_icon: images/favicon.ico
site_subtitle: Java | Spring Boot | Spring Batch | ETL
site_keywords: Java, Spring Boot, Spring Batch, ETL, Microservices, Technical Documentation

nav:
  - üî∂lombok mvn git: 00_others.md
  - üî∂Java: 00_java-evolution.md
  - üî∂Spring:
      - ‚úîÔ∏èCore:
          - Spring Core Basics: 01_Spring-core/01_Spring_Core.md
          - Spring Bean Lifecycle: 01_Spring-core/02_Spring_bean_lifeCycle.md
          - AOP Concept: 01_Spring-core/03_AOP_concept.md
          - Point-cut Examples: 01_Spring-core/03_point-cut-examples.txt
          - Spring Properties: 01_Spring-core/04_spring_properties.md

      - ‚úîÔ∏èSpringBoot:
          - Kickoff: 01_springboot/01_SB_kickoff.md
          - Auto Configuration: 01_springboot/02_SB_AutoConfig.md
          - Starter & Testing: 01_springboot/03_SB_starter_test.md

      - ‚úîÔ∏èSpringBatch:
          - SpringBatch1: 05_spring-batch-ETL/00_index.md
          - SpringBatch2: 05_spring-batch-ETL/01_SpringBatch-start.md

  - üî∂Web Application:
      - ‚úîÔ∏ècontroller:
          - Web Start: 02_web/00 WEB_start.md
          - General Web Tasks: 02_web/00_general_web_task.md
          - Servlet 3: 02_web/01_servlet_3.md
          - Spring MVC: 02_web/02_spring_MVC.md
          - Spring Boot Starter Web: 02_web/03_spring_boot_stater_web.md
          - REST: 02_web/04_REST.md
          - Jackson: 02_web/05_Jackson.md
          - Swagger: 02_web/06_swagger.md
          - Error Handling: 02_web/07_error_handling.md
          - gRPC & Webflux: 02_web/08_gRPC+webflux.md
          - Webflux: 02_web/09_webflux.md

      - ‚úîÔ∏èData Layer:
          - Common Tasks: 03_data-layer/00_common_task.md
          - JPA: 03_data-layer/01_JPA.md
          - Persistence Context: 03_data-layer/02_presistence-context.md
          - Hibernate Annotations & Converter: 03_data-layer/04_Hibernate-1-anno+converter.md
          - Hibernate Identifier & Validator: 03_data-layer/04_Hibernate-2-identifier+validator.md
          - Hibernate Query: 03_data-layer/04_Hibernate-3-query.md
          - SB JPA Data Part 1: 03_data-layer/05-SBjpaData-1-start.md
          - SB JPA Data Part 2: 03_data-layer/05-SBjpaData-2.md
          - SB JPA Data Transactions: 03_data-layer/05-SBjpaData-3-txn.md
          - ER Diagram: 03_data-layer/er-diagram.png

      - ‚úîÔ∏èSecurity:
          - Concepts: 04_security/01_01_Concepts.md
          - LDAP: 04_security/01_03_LDAP.md

  - üî∂Learning and POCS:
      - ‚úîÔ∏è2025:
          - 01 Stream performance: 2025/01_java-streams-performance.md
          - 02_java-virtual-thread: 2025/02_java-virtual-thread.md
          - 03_Streaming-response: 2025/03_Streaming-response.md
          - 04_temporal_ms-workflow: 2025/04_temporal_ms-workflow.md
          - 05_Spring_modulith: 2025/05_Spring_modulith.md
          - 06_Java-streams-gatherer: 2025/06_Java-streams-gatherer.md
      - ‚úîÔ∏è2026:
          - 01_01_SpringBoot-v4: 2026/01_01_SpringBoot-v4.md
          - 02_01_SpringAI-start: 2026/02_01_SpringAI-start.md

extra_css:
  - mkdocs.css

theme:
  name: material
  features:
    #- content.code.annotate
    - navigation.tracking          # Enables breadcrumbs
    - navigation.tabs              # Optional: if using tabs layout
    - navigation.top               # Scroll-to-top button
    - navigation.sections
    #- navigation.expand
    - navigation.indexes
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: pink
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: grey
      accent: pink


repo_url: https://github.com/lekhrajdinkar/solution-engineer
repo_name: GitHub
edit_uri: edit/main/Notes/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/

